// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250223054724_UpdateBooking")]
    partial class UpdateBooking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalPricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            DateAdded = new DateTime(2025, 2, 23, 5, 47, 23, 774, DateTimeKind.Utc).AddTicks(377),
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            Picture = "/pictures/Toyota-Corolla.jpg",
                            RentalPricePerDay = 5000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            DateAdded = new DateTime(2025, 2, 23, 5, 47, 23, 774, DateTimeKind.Utc).AddTicks(652),
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Civic",
                            Picture = "/pictures/Honda-Civic.jpg",
                            RentalPricePerDay = 5500m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Color = "Red",
                            DateAdded = new DateTime(2025, 2, 23, 5, 47, 23, 774, DateTimeKind.Utc).AddTicks(656),
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Mustang",
                            Picture = "/pictures/Ford-Mustang.jpg",
                            RentalPricePerDay = 12000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Color = "Blue",
                            DateAdded = new DateTime(2025, 2, 23, 5, 47, 23, 774, DateTimeKind.Utc).AddTicks(659),
                            IsAvailable = false,
                            Make = "Tesla",
                            Model = "Model 3",
                            Picture = "/pictures/Tesla-Model3.jpg",
                            RentalPricePerDay = 7000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Color = "Grey",
                            DateAdded = new DateTime(2025, 2, 23, 5, 47, 23, 774, DateTimeKind.Utc).AddTicks(662),
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X5",
                            Picture = "/pictures/BMW-X5.jpg",
                            RentalPricePerDay = 9000m,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("backend.Models.CarDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("CarDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Category = "Sedan",
                            DiscountPercentage = 10,
                            FuelType = "Petrol",
                            Mileage = 18,
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Category = "Sedan",
                            DiscountPercentage = 5,
                            FuelType = "Petrol",
                            Mileage = 17,
                            SeatingCapacity = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Category = "Sports",
                            DiscountPercentage = 15,
                            FuelType = "Petrol",
                            Mileage = 12,
                            SeatingCapacity = 4,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Category = "Electric",
                            FuelType = "Electric",
                            Mileage = 400,
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Category = "SUV",
                            DiscountPercentage = 8,
                            FuelType = "Diesel",
                            Mileage = 15,
                            SeatingCapacity = 7,
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Report")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            DateCreated = new DateTime(2025, 2, 23, 5, 47, 23, 772, DateTimeKind.Utc).AddTicks(3144),
                            Email = "arhamkalam@admin.com",
                            PasswordHash = "GD@Arhamkala2025madmin@123#AK",
                            Report = false,
                            Role = "Admin",
                            Username = "ArhamAdmin"
                        },
                        new
                        {
                            Id = 2000,
                            DateCreated = new DateTime(2025, 2, 23, 5, 47, 23, 772, DateTimeKind.Utc).AddTicks(3449),
                            Email = "user@gmail.com",
                            PasswordHash = "GD@User2025@123#AK",
                            Report = false,
                            Role = "User",
                            Username = "User"
                        });
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.CarDetails", b =>
                {
                    b.HasOne("backend.Models.Car", "Car")
                        .WithOne("CarDetails")
                        .HasForeignKey("backend.Models.CarDetails", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("backend.Models.Car", b =>
                {
                    b.Navigation("CarDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
